services:
  - type: web
    name: furia-chat
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn project.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    static:
      - type: static
        name: static
        path: /static
        dir: staticfiles


